update readme
thomasbtf/document-anonymization pull request #37
Opened 2021-04-29 08:34 UTC by thomasbtf

2021-04-29 09:18 UTC, simakro requested changes

2021-04-29 09:18 UTC, simakro commented on config/pep/documents.csv
> +2,/local/data/dev/thomas/document-anonymization/data/1021088060.23247710.patient.json,/local/data/dev/thomas/document-anonymization/data/1021088060.20210420.docs.tar.lz4
Ich denke das ist ein versehen. Die wollen wir ja nicht online

2021-04-29 09:20 UTC, thomasbtf commented on config/pep/documents.csv
> +2,/local/data/dev/thomas/document-anonymization/data/1021088060.23247710.patient.json,/local/data/dev/thomas/document-anonymization/data/1021088060.20210420.docs.tar.lz4
correct, changed this in b4607c8

2021-04-30 08:26 UTC, simakro approved these changes

2021-04-30 08:26 UTC, merged